### ISSUE TITLE
Dataset name is invalid

### ISSUE THREAD

**Issue by kfrancis** [geckoboard/sql-dataset#16]
Can't seem to get this to work, it's complaining about the dataset name for some reason:

> Following errors occurred with the config;
>  - Dataset name is invalid, should be 3 or more characters with only lowercase alphanumeric characters, dots, hyphens, and underscores

Config:
```
geckoboard_api_key: <redacted>
database:
 driver: mssql
 host: localhost
 username: geckoboard
 password: <redacted>
 name: <redacted>
refresh_time_sec: 60
datasets:
 - name: edtActivity
   update_type: replace
   sql: SELECT top 10 CreatedAt, nConnections from EDTRecords.MOHConnectionLog
   fields:
    - type: date
      name: CreatedAt
    - type: number
      name: nConnections
```
