### ISSUE TITLE
Underscores in dataset names breaks unique_by

### ISSUE THREAD

**Issue by SirRawlins** [geckoboard/sql-dataset#22]
I've been pushing some data up using this tool today, but kept coming across an error message which said something akin to:

> There was an error sending the data to Geckoboard's API: You cannot use "subscribed_at" in "unique_by" as this field is not defined in the dataset.

This seemed curious to me, as my query, and dataset both have a field named "subscribed_at".

```yml
  - name: subscriptions.all
    update_type: append
    sql: >
      SELECT date_trunc('day', publisher_subscriptions.created_at) subscribed_at,
             publisher_subscriptions.type,
             COUNT(publisher_subscriptions.id)
      FROM publisher_subscriptions
      GROUP BY 1, publisher_subscriptions.type
      ORDER BY 1 DESC
    fields:
      - type: datetime
        name: subscribed_at
      - type: string
        name: type
      - type: number
        name: count
    unique_by:
      - subscribed_at
      - type
```

After downloading and running the debug build, I can see that the compiled request body pulls the underscore out, and uses a key named "subscribedat" - probably during it's serialization through yml, or json.

It seems that using "subscribedat" in my "unique_by" get's things working, but took a while to figure out. 😄

**Comment by jaydiablo** [comment]
I've found that you can force the `key` of the field to what you want it to be, `subscribed_at` in this case, instead of relying on the automatic key generation:

```yaml
- name: subscriptions.all
    update_type: append
    sql: >
      SELECT date_trunc('day', publisher_subscriptions.created_at) subscribed_at,
             publisher_subscriptions.type,
             COUNT(publisher_subscriptions.id)
      FROM publisher_subscriptions
      GROUP BY 1, publisher_subscriptions.type
      ORDER BY 1 DESC
    fields:
      - type: datetime
        name: subscribed_at
        key: subscribed_at
      - type: string
        name: type
      - type: number
        name: count
    unique_by:
      - subscribed_at
```

Then you can use more friendly names for the `name` property, like "Subscribed Day".
